### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by jeredding** [slank/n2cw#1]
When installing from pip, there's an error: 

```
/opt/scripts/cw_metrics/bin/pip run on Wed Feb 11 18:09:40 2015
Downloading/unpacking n2cw

  Getting page https://pypi.python.org/simple/n2cw/
  URLs to search for versions for n2cw:
  * https://pypi.python.org/simple/n2cw/
  Analyzing links from page https://pypi.python.org/simple/n2cw/
    Skipping link https://pypi.python.org/packages/2.7/n/n2cw/n2cw-0.1.1-py2.py3-none-any.whl#md5=bd6c2ce436779bc0e9c7c5bfc08a5d07 (from https://pypi.python.org/simple/n2cw/); unknown archive format: .whl
    Found link https://pypi.python.org/packages/source/n/n2cw/n2cw-0.1.1.tar.gz#md5=310850df4c3f6ac0c45a37f04852875c (from https://pypi.python.org/simple/n2cw/), version: 0.1.1
  Downloading n2cw-0.1.1.tar.gz

  Downloading from URL https://pypi.python.org/packages/source/n/n2cw/n2cw-0.1.1.tar.gz#md5=310850df4c3f6ac0c45a37f04852875c (from https://pypi.python.org/simple/n2cw/)
  Running setup.py egg_info for package n2cw

    Traceback (most recent call last):

      File "<string>", line 16, in <module>

      File "/opt/scripts/cw_metrics/build/n2cw/setup.py", line 23, in <module>

        long_description=read('README.md'),

      File "/opt//scripts/cw_metrics/build/n2cw/setup.py", line 11, in read

        return open(os.path.join(os.path.dirname(__file__), fname)).read()

    IOError: [Errno 2] No such file or directory: '/opt//scripts/cw_metrics/build/n2cw/README.md'

    Complete output from command python setup.py egg_info:

    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/opt/scripts/cw_metrics/build/n2cw/setup.py", line 23, in <module>

    long_description=read('README.md'),

  File "/opt/scripts/cw_metrics/build/n2cw/setup.py", line 11, in read

    return open(os.path.join(os.path.dirname(__file__), fname)).read()

IOError: [Errno 2] No such file or directory: '/opt/scripts/cw_metrics/build/n2cw/README.md'

----------------------------------------

Command python setup.py egg_info failed with error code 1 in /opt/scripts/cw_metrics/build/n2cw

Exception information:
Traceback (most recent call last):
  File "/opt/scripts/cw_metrics/lib/python2.7/site-packages/pip/basecommand.py", line 139, in main
    status = self.run(options, args)
  File "/opt//scripts/cw_metrics/lib/python2.7/site-packages/pip/commands/install.py", line 266, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/opt/scripts/cw_metrics/lib/python2.7/site-packages/pip/req.py", line 1057, in prepare_files
    req_to_install.run_egg_info()
  File "/opt/scripts/cw_metrics/lib/python2.7/site-packages/pip/req.py", line 236, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/opt/scripts/cw_metrics/lib/python2.7/site-packages/pip/util.py", line 662, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command python setup.py egg_info failed with error code 1 in /opt/scripts/cw_metrics/build/n2c
```

**Comment by slank** [comment]
Hmm. I don't get the same error:

```
me@here:~$ mkvirtualenv foo
New python executable in foo/bin/python2.7
Also creating executable in foo/bin/python
Installing setuptools, pip...done.
(foo)me@here:~$ pip install n2cw
Downloading/unpacking n2cw
  Downloading n2cw-0.1.1-py2.py3-none-any.whl
Downloading/unpacking botocore>=0.80.0 (from n2cw)
  Downloading botocore-0.87.0.tar.gz (1.3MB): 1.3MB downloaded
  Running setup.py (path:/Users/me/virtualenvs/foo/build/botocore/setup.py) egg_info for package botocore

Downloading/unpacking jmespath==0.6.1 (from botocore>=0.80.0->n2cw)
  Downloading jmespath-0.6.1.tar.gz
  Running setup.py (path:/Users/me/virtualenvs/foo/build/jmespath/setup.py) egg_info for package jmespath

Downloading/unpacking python-dateutil>=2.1,<3.0.0 (from botocore>=0.80.0->n2cw)
  Downloading python_dateutil-2.4.0-py2.py3-none-any.whl (175kB): 175kB downloaded
Downloading/unpacking six>=1.5 (from python-dateutil>=2.1,<3.0.0->botocore>=0.80.0->n2cw)
  Downloading six-1.9.0-py2.py3-none-any.whl
Installing collected packages: n2cw, botocore, jmespath, python-dateutil, six
  Running setup.py install for botocore

  Running setup.py install for jmespath
    changing mode of build/scripts-2.7/jp from 644 to 755

    changing mode of /Users/me/virtualenvs/foo/bin/jp to 755
Successfully installed n2cw botocore jmespath python-dateutil six
Cleaning up...
```

That's on a MacOS 10.10.2 system using python 2.7.9 from Homebrew. Also tested on Ubuntu 14.04 using the system python/pip outside a virtualenv.

**Comment by slank** [comment]
Looking more closely, I see `Downloading n2cw-0.1.1.tar.gz` whereas my installation downloaded the whl file. Perhaps I the tar.gz I pushed is bad. I'll re-upload.
